### PR TITLE
Github repositories dataset 

### LINKED ISSUE #376: List of FD properties and associated info e.g. traffic
Get list of properties (i.e. something that is on web and gets traffic) and associated info including traffic stats.

Why? For purposes of improving website etc #373 we want to know what we have and what is being used ...

## Acceptance criteria

* [x] Spreadsheet list of main properties other than github repos ...  (plus key columns)
https://github.com/frictionlessdata/project/issues/376#issuecomment-565317015
* [x] CSV of all the repos with their traffic that we could merge in (separate for now as we automate this part probably). --> https://github.com/monikappv/frictionless-data-repos
@monikappv 
   * Bonus for having:
     * url of repo
     * title / description
     * link from repo
   * Bonus for making this a data package
https://github.com/frictionlessdata/project/issues/376#issuecomment-564970945

## Tasks

* [x] Get list of 88 repos
* [x] Get their traffic -- see below on how
  * [x] do for one
  * [x] do for all

### How to get github repo traffic via API

```
curl -u {your-name} https://api.github.com/repos/frictionlessdata/specs/traffic/views
```

image
### The data package

https://github.com/monikappv/frictionless-data-repos

### The script in gist

https://gist.github.com/monikappv/9cbdd0de851c8ed7261a57475eac68e6

### PR DESCRIPTION
**Pull request by monikappv**
* This PR fixes https://github.com/frictionlessdata/project/issues/376
* No bugs fixed, added a new feature instead
* Added a data package containing a script that extracts key data for the github repositories of a given user or organization and loads them into a CSV file
* Key repo data: slug, title, description, type, link to repo, url, number of clones, number of views, number of unique views, number of watchers, number of stars, number of open issues

csvscreenshot

---

Please preserve this line to notify @lwinfree (lead of this repository)

### CODE REVIEW

**Comment by rufuspollock** [comment]
@monikappv @cabral hmmm great we have this.

Generally the PM repo should *not* have stuff in it other than PM related info (e.g. a README intro and maybe some process related info).

This is content related to answering a specific item and is not general PM info.

I suggest this stuff go into a gist - or a dedicated repo.

**Comment by monikappv** [comment]
@rufuspollock 

Where should I create a repo and put the stuff in?
a. Frictionlessdata 
**b. Datopian** (since this is not necesserily connected to fd.io)

**Comment by rufuspollock** [comment]
@monikappv why not put this in a gist to start with so we don't even have to worry about this question ...

**Comment by monikappv** [comment]
@rufuspollock https://gist.github.com/monikappv/9cbdd0de851c8ed7261a57475eac68e6

**Comment by rufuspollock** [comment]
Great. Please post that in the relevant issue as well. Now closing this PR.

**Comment by monikappv** [comment]
@rufuspollock it is already there

**Pull request closed without merging**
