### PR TITLE
Apply OKFN brand guidelines

### LINKED ISSUE #828: Design update to match new OKFN brand guidelines
- [x] Update logo on the header to:
https://drive.google.com/file/d/1xz1SDI4A2uk_1NRM6nYbq2CYwzqM59fp/view?usp=sharing

- [x] Update favicon to:
https://drive.google.com/drive/folders/1xzOCkHeP5FBNlu7EqbfipNyqpylo8ibB?usp=sharing

- [x] Replace colors across the entire website:
These are the main ones. But please let me know what other colors are listed in the CSS and I will suggest replacements.

	`#ea6d4c` to `#00d1ff`
	`#cc785f` to `#e077ff`
	`#e8e8e8` to `#f8f8f8`
`#cfe1e6` to `#adffed`

- [x] Replace font-family with HK Grotesk (respecting the different weights):
Files available here: https://drive.google.com/file/d/11ffEezgjG3WeRdkk_0gMW71PpjdztVw0/view?usp=sharing

---

- [ ] Add OKFN expandable top header
(The same updated version displayed on sites like [opendefinition.org](http://opendefinition.org) and [opendatacommons.org](http://opendatacommons.org))
- [ ] Change the main illustration on the homepage to:
https://drive.google.com/file/d/1035n9tVNq3Y3BURxBsdaf93gT54bhjT6/view?usp=sharing

### PR DESCRIPTION
**Pull request by shashigharti**
# Overview

Applied style to match OKFN brand guidelines

- color 
- headings
- logo
- font

fixes #828
 #220 

@roll @lucpretti Output after the changes.

frontpage

### CODE REVIEW

**Comment by lucpretti** [comment]
Thank you @shashigharti, it looks good!

Three changes only:

- [x] Replace FD logo in the footer with this b/w version here: https://drive.google.com/file/d/1ybxCJ8Xp_iEE4_4M2ejLf0pSx7x3-D08/view?usp=sharing
- [x] Replace OKFN logo in the footer with this b/w version here: https://drive.google.com/file/d/1h6yRR80ibQMCGuipe-TZs22c8ID9j6_Y/view?usp=sharing
- [x] Replace the orange colour `#cc785f` with our brand purple `#e077ff`

**Comment by roll** [comment]
@sapetti9 
@shashigharti 
Let's remove the "Frictionless Projects" section from the main page -- it's already outdated and will be loosing actuality even more going forward. Without this section it will looks more neutral, software and standards, for anyone who works with data etc

**Comment by roll** [comment]
@shashigharti 
Can you please merge yourself and check that it's deployed when Lucas' comment is addressed?

**Comment by shashigharti** [comment]
@lucpretti along those I have also made changes to 

- fonts (family, size, color)
- Svg image color
- Blurred circles

For remaning two, I got instruction from @roll to work on it later.

**Comment by roll** [comment]
@shashigharti 
I mean this one - https://github.com/frictionlessdata/frictionlessdata.io/pull/830#issuecomment-1742571208

In-general we're splitting #828 into two parts. In this PR we are addressing the most critical branding parts

**Comment by shashigharti** [comment]
Thanks @roll and @lucpretti and I will make the changes.

**Comment by shashigharti** [comment]
@lucpretti @roll I made the changes, and here is the output after new changes.

frictionlessdata-io

**Comment by lucpretti** [comment]
Looks great, thank you @shashigharti!

Could we just decrease the FD logo size in the footer a little bit to normalise it with the other two?

**Comment by shashigharti** [comment]
@lucpretti I have made the changes.
logo

**Comment by shashigharti** [comment]
Thanks @lucpretti . Shall I merge it?

**Comment by lucpretti** [comment]
For me it's good to go.

**Pull request merged**
